name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Create ZIP file
        run: |
          cd custom_components/daily_brief
          zip -r ../../daily_brief.zip .

      - name: Upload ZIP to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: daily_brief.zip
          asset_name: daily_brief.zip
          tag: ${{ github.ref }}
          overwrite: true
